language: python

python:
  3.6.9

services:
  MongoDB 4.2.5
  Firebase 3.0.1
  PyMongo 3.10.1

sudo: required

install:
  pip3 install -r requirements.txt

before_script:
  sudo systemctl enable mongod.service
  sudo systemctl start mongod.service
  # Only for testing
  python3 backup/autobackup.py
  
script:
  python3 index.py